[test]
root = "."
coverage = true
coverageReporter = ["text"]
coverageSkipTestFiles = true
coverageThreshold = { functions = 1.0, lines = 1.0 }
coveragePathIgnorePatterns = [
  "**/__tests__/**",
  "tests/**",
  "**/main.*",
  "**/root/wiring.*",
]

[run]
bun = true
