import type { Files } from './constitution.fixtures';

const GOLDEN_INDEX = `${[
  '# generated by bun run digests:write — do not edit',
  'role\tformat\tfalse',
  'role\tlint\tfalse',
  'role\ttypes\tfalse',
  'role\tarchitecture\tfalse',
  'role\tnames\ttrue',
  'role\tunused\tfalse',
  'role\tversions\tfalse',
  'role\ttests\tfalse',
  'role\tcoverage\tfalse',
  'role\tmutation\tfalse',
  'role\tsecrets\ttrue',
  'role\taudit\tfalse',
  'block\tcore\tcore\tThe core block.\tprinciples.md\t\t\t\tfalse\t\t\t\t\t',
  'block\ti18n\tdomain\tThe i18n block.\t\t\t\t\tfalse\t\t\t\t\t',
  'block\tremote-data\tdomain\tThe remote-data block.\t\t\t\t\tfalse\t\t\t\t\t',
  'block\tui\tdomain\tThe ui block.\t\tremote-data\t\t\tfalse\t\t\t\t\t**/ui/**',
  'block\tuntrusted-client\tdomain\tThe untrusted-client block.\t\t\t\t\tfalse\t\t\t\t\t',
  'block\tbrowser\tplatform\tThe browser block.\t\t\tuntrusted-client\t\tfalse\t\t\t\t\t',
  'block\ttypescript\tlanguage\tThe typescript block.\t\t\t\t\tfalse\t\ttypes\ttypescript\t\t',
  'block\t_react\timplementation\tThe _react block.\t\t\tui\t\ttrue\treact-dom\t\t\t\t',
  'block\tbiome\timplementation\tThe biome block.\t\t\ttypescript\t\tfalse\t\tformat lint\ttypescript\t\t',
  'block\tlingui\timplementation\tThe lingui block.\t\t\ti18n typescript\t\tfalse\t\t\ttypescript\t\t',
  'block\treact-dom\timplementation\tThe react-dom block.\t\t\tbrowser\t_react\tfalse\t\t\t\t_react\t',
  'rule\trules-bind\tcore\tblocks/core/core.md\t\tMUST\treview\t\t\tarchitecture\tThe rules-bind rule holds.',
  'rule\tdependencies-point-inward\tcore\tblocks/core/principles.md\t\tMUST\treview\t\t\tarchitecture\tThe dependencies-point-inward rule holds.',
  'rule\ti18n-plurals-by-cldr\ti18n\tblocks/domains/i18n/i18n.md\t\tMUST\treview\t\t\tux\tThe i18n-plurals-by-cldr rule holds.',
  'rule\treads-are-cancellable\tremote-data\tblocks/domains/remote-data/remote-data.md\t\tMUST\treview\t\t\tdata\tThe reads-are-cancellable rule holds.',
  'rule\tfour-data-states\tui\tblocks/domains/ui/ui.md\t\tMUST\ttest\t\t\tux a11y\tThe four-data-states rule holds.',
  'rule\toptimistic-writes-roll-back\tui\tblocks/domains/ui/with/remote-data.md\tremote-data\tMUST\treview\t\t\tux data\tThe optimistic-writes-roll-back rule holds.',
  'rule\tno-secret-in-the-client\tuntrusted-client\tblocks/domains/untrusted-client/untrusted-client.md\t\tMUST\treview\t\t\tsecurity\tThe no-secret-in-the-client rule holds.',
  'rule\tno-window-during-render\tbrowser\tblocks/contexts/platforms/browser/browser.md\t\tMUST\treview\t\t\tarchitecture\tThe no-window-during-render rule holds.',
  'rule\tno-any\ttypescript\tblocks/contexts/languages/typescript/typescript.md\t\tMUST\ttool\ttypes\ttypescript\ttypes\tA TypeScript value is never typed `any`.',
  'rule\thooks-at-top-level\t_react\tblocks/implementations/_react/_react.md\t\tMUST\ttool\tlint\t\tarchitecture\tA React hook is called only at the top level.',
  'rule\tportals-for-overlays\treact-dom\tblocks/implementations/react-dom/react-dom.md\t\tMUST\treview\t\t\tarchitecture\tReact DOM renders an overlay through a portal.',
  'answer\tlingui\ti18n-plurals-by-cldr\tmet',
].join('\n')}\n`;

const GOLDEN_CORE = [
  '# Core',
  '',
  'Read [principles](blocks/core/principles.md).',
  '',
  '## rules-bind · MUST',
  'The rules-bind rule holds.',
  '**Why:** it keeps the code honest.',
  '**Check:** review',
  '**Tags:** architecture',
  '',
  'Laws: dependencies-point-inward.',
  '',
].join('\n');

// The digests of the valid constitution, written out by hand: the digests check
// and the generator's specs compare against them.
const digestFiles = (): Files => ({
  'digests/core.md': GOLDEN_CORE,
  'digests/index.tsv': GOLDEN_INDEX,
});

export { digestFiles, GOLDEN_CORE, GOLDEN_INDEX };
