import type { Files } from './constitution.fixtures';

const GOLDEN_INDEX = `${[
  '# generated by bun run digests:write — do not edit',
  'role\tformat\tfalse',
  'role\tlint\tfalse',
  'role\ttypes\tfalse',
  'role\timports\tfalse',
  'role\tnames\ttrue',
  'role\tunused\tfalse',
  'role\tversions\tfalse',
  'role\ttests\tfalse',
  'role\tcoverage\tfalse',
  'role\tmutation\tfalse',
  'role\tsecrets\ttrue',
  'role\taudit\ttrue',
  'role\tcommits\ttrue',
  'block\tcore\tcore\tThe core block.\tfoundation/principles.md workflow/workflow.md\t\t\t\tfalse\t\t\t\t\t\t',
  'block\ti18n\tdomain\tThe i18n block.\tfoundation/i18n.md\t\t\t\tfalse\t\t\t\t\t\t',
  'block\tremote-data\tdomain\tThe remote-data block.\tarchitecture/remote-data.md\t\t\t\tfalse\t\t\t\t\t\t',
  'block\tui\tdomain\tThe ui block.\tfoundation/ui.md\tarchitecture/remote-data\t\t\tfalse\t\t\t\t\t\t**/ui/**',
  'block\tuntrusted-client\tdomain\tThe untrusted-client block.\tfoundation/untrusted-client.md\t\t\t\tfalse\t\t\t\t\t\t',
  'block\tbrowser\tplatform\tThe browser block.\tarchitecture/browser.md\t\tuntrusted-client\t\tfalse\t\t\t\t\t\t',
  'block\ttypescript\tlanguage\tThe typescript block.\tfoundation/typescript.md\t\t\t\tfalse\t\ttypes\ttypescript\tformat lint types imports names unused versions tests coverage mutation secrets audit commits\t\t',
  'block\t_react\timplementation\tThe _react block.\tfoundation/hooks.md\t\tui\t\ttrue\treact-dom\t\t\t\t\t',
  'block\tbiome\timplementation\tThe biome block.\t\t\ttypescript\t\tfalse\t\tformat lint\ttypescript\t\t\t',
  'block\tlingui\timplementation\tThe lingui block.\t\t\ti18n typescript\t\tfalse\t\t\t\t\t\t',
  'block\treact-dom\timplementation\tThe react-dom block.\tworkflow/portals.md\t\tbrowser\t_react\tfalse\t\t\t\t\t_react\t',
  'rule\tdependencies-point-inward\tcore\tblocks/core/foundation/principles.md\t\tMUST\treview\t\t\t\tfoundation\t\ttrue',
  'rule\trules-bind\tcore\tblocks/core/workflow/workflow.md\t\tMUST\treview\t\t\t\tworkflow\t\ttrue',
  'rule\ti18n-plurals-by-cldr\ti18n\tblocks/domains/i18n/foundation/i18n.md\t\tMUST\treview\t\t\tux\tfoundation\t\ttrue',
  'rule\treads-are-cancellable\tremote-data\tblocks/domains/remote-data/architecture/remote-data.md\t\tMUST\treview\t\t\tdata\tarchitecture\t\ttrue',
  'rule\tfour-data-states\tui\tblocks/domains/ui/foundation/ui.md\t\tMUST\ttest\t\t\tux a11y\tfoundation\t\ttrue',
  'rule\toptimistic-writes-roll-back\tui\tblocks/domains/ui/architecture/with/remote-data.md\tremote-data\tMUST\treview\t\t\tux data\tarchitecture\treads-are-cancellable\tfalse',
  'rule\tno-secret-in-the-client\tuntrusted-client\tblocks/domains/untrusted-client/foundation/untrusted-client.md\t\tMUST\treview\t\t\tsecurity\tfoundation\t\ttrue',
  'rule\tno-window-during-render\tbrowser\tblocks/contexts/platforms/browser/architecture/browser.md\t\tMUST\treview\t\t\t\tarchitecture\t\ttrue',
  'rule\tno-any\ttypescript\tblocks/contexts/languages/typescript/foundation/typescript.md\t\tMUST\ttool\ttypes\ttypescript\t\tfoundation\t\ttrue',
  'rule\thooks-at-top-level\t_react\tblocks/implementations/_react/foundation/hooks.md\t\tMUST\ttool\tlint\t\t\tfoundation\t\ttrue',
  'rule\tportals-for-overlays\treact-dom\tblocks/implementations/react-dom/workflow/portals.md\t\tMUST\treview\t\t\t\tworkflow\t\ttrue',
  'answer\tlingui\ti18n-plurals-by-cldr\tyes',
].join('\n')}\n`;

const GOLDEN_CORE = [
  '# Core',
  '',
  'Read [principles](blocks/core/foundation/principles.md).',
  '',
].join('\n');

// The digests of the valid constitution, written out by hand: the digests check
// and the generator's specs compare against them.
const digestFiles = (): Files => ({
  'digests/core.md': GOLDEN_CORE,
  'digests/index.tsv': GOLDEN_INDEX,
});

export { digestFiles, GOLDEN_CORE, GOLDEN_INDEX };
