import { Layer } from '#/kernel';

import type { Block, Constitution, RequirementAnswer, Rule } from '../../../entities';
import { BlockFileRole } from '../../../entities';
import type { BlocksById } from '../../../utils';
import { axisFolderOf, fileNameOf } from '../../../utils';
import { ancestorsOf } from './ancestors.utils';

const TAB = '\t';
const LIST = ' ';
const HEADER = '# generated by bun run digests:write — do not edit';

const recordOf = (fields: readonly string[]): string => fields.join(TAB);

const blockRecord = (input: {
  block: Block;
  blocks: readonly Block[];
  byId: BlocksById;
}): string => {
  const { block } = input;

  return recordOf([
    'block',
    block.id,
    block.layer,
    block.frontMatter.summary,
    block.files
      .filter((file) => file.role === BlockFileRole.Chapter)
      .map((file) => `${axisFolderOf(file.axis)}${fileNameOf(file.path)}`)
      .join(LIST),
    block.files
      .flatMap((file) =>
        file.with === undefined
          ? []
          : [
              `${axisFolderOf(file.axis)}${file.with}`,
            ],
      )
      .join(LIST),
    block.frontMatter.requires.join(LIST),
    block.frontMatter.extends ?? '',
    String(block.frontMatter.abstract),
    input.blocks
      .filter((heir) => heir.frontMatter.extends === block.id)
      .map((heir) => heir.id)
      .join(LIST),
    block.frontMatter.languages.join(LIST),
    ancestorsOf({
      blockId: block.id,
      byId: input.byId,
    }).join(LIST),
    block.frontMatter.governs.join(LIST),
  ]);
};

const GOVERNS = '> Governs ';

const governsOf = (body: string): string =>
  body
    .split('\n')
    .find((line) => line.startsWith(GOVERNS))
    ?.slice(GOVERNS.length) ?? '';

// Each chapter of core with what its Governs line names, which the digest
// prints beside the chapter's name.
const chapterRecords = (block: Block): readonly string[] =>
  block.files
    .filter((file) => file.role === BlockFileRole.Chapter)
    .map((file) =>
      recordOf([
        'chapter',
        block.id,
        `${axisFolderOf(file.axis)}${fileNameOf(file.path)}`,
        governsOf(file.body),
      ]),
    );

const ruleRecord = (rule: Rule): string =>
  recordOf([
    'rule',
    rule.slug,
    rule.block,
    rule.file,
    rule.with ?? '',
    rule.level,
    rule.tags.join(LIST),
    axisFolderOf(rule.axis).slice(0, -1),
    rule.parent ?? '',
    String(rule.statedLevel !== undefined),
  ]);

const answerRecord = (answer: RequirementAnswer): string =>
  recordOf([
    'answer',
    answer.block,
    answer.requirement,
    answer.met,
  ]);

const indexOf = (input: { byId: BlocksById; constitution: Constitution }): string =>
  `${[
    HEADER,
    ...input.constitution.blocks.map((block) =>
      blockRecord({
        block,
        blocks: input.constitution.blocks,
        byId: input.byId,
      }),
    ),
    ...input.constitution.blocks
      .filter((block) => block.layer === Layer.Core)
      .flatMap(chapterRecords),
    ...input.constitution.rules.map(ruleRecord),
    ...input.constitution.requirementAnswers.map(answerRecord),
  ].join('\n')}\n`;

export { indexOf };
