import { LANGUAGE_FREE_ROLES, ROLES } from '#/kernel';

import type {
  Block,
  Constitution,
  RequirementAnswer,
  Rule,
} from '../../../entities';
import { BlockFileRole } from '../../../entities';
import type { BlocksById } from '../../../utils';
import {
  checkOf,
  fileNameOf,
  languagesOf,
  rewriteLocalLinks,
  ruleLanguagesOf,
  targetFromRoot,
} from '../../../utils';
import { ancestorsOf } from './ancestors.utils';
import { headlineOf } from './headline.utils';

const TAB = '\t';
const LIST = ' ';
const HEADER = '# generated by bun run digests:write — do not edit';

const languageFree: readonly string[] = LANGUAGE_FREE_ROLES;

const recordOf = (fields: readonly string[]): string => fields.join(TAB);

// The hook reads the roles from here, never from a list of its own: a tool with
// no language checks only the language-free ones (spec §2).
const roleRecords = (): readonly string[] =>
  ROLES.map((role) =>
    recordOf([
      'role',
      role,
      String(languageFree.includes(role)),
    ]),
  );

const blockRecord = (input: {
  block: Block;
  blocks: readonly Block[];
  byId: BlocksById;
}): string => {
  const { block } = input;

  return recordOf([
    'block',
    block.id,
    block.layer,
    block.frontMatter.summary,
    block.files
      .filter((file) => file.role === BlockFileRole.Chapter)
      .map((file) => `${file.axis}/${fileNameOf(file.path)}`)
      .join(LIST),
    block.files
      .flatMap((file) =>
        file.with === undefined
          ? []
          : [
              `${file.axis}/${file.with}`,
            ],
      )
      .join(LIST),
    block.frontMatter.requires.join(LIST),
    block.frontMatter.extends ?? '',
    String(block.frontMatter.abstract),
    input.blocks
      .filter((heir) => heir.frontMatter.extends === block.id)
      .map((heir) => heir.id)
      .join(LIST),
    block.frontMatter.checks.join(LIST),
    languagesOf({
      blockId: block.id,
      byId: input.byId,
    }).join(LIST),
    ancestorsOf({
      blockId: block.id,
      byId: input.byId,
    }).join(LIST),
    block.frontMatter.governs.join(LIST),
  ]);
};

const ruleRecord = (input: { byId: BlocksById; rule: Rule }): string => {
  const { rule } = input;
  const check = checkOf(rule);

  return recordOf([
    'rule',
    rule.slug,
    rule.block,
    rule.file,
    rule.with ?? '',
    rule.level,
    check.kind === 'unknown' ? '' : check.kind,
    // Stryker disable next-line ConditionalExpression: join writes a missing role as empty
    check.kind === 'tool' ? check.role : '',
    ruleLanguagesOf(input).join(LIST),
    rule.tags.join(LIST),
    rule.axis,
    rule.parent ?? '',
    String(rule.statedLevel !== undefined),
    // The digest has no folder, so a link in the headline is read from the root.
    rewriteLocalLinks({
      rewrite: (target: string): string =>
        targetFromRoot({
          path: rule.file,
          target,
        }),
      text: headlineOf(rule.statement),
    }),
  ]);
};

const answerRecord = (answer: RequirementAnswer): string =>
  recordOf([
    'answer',
    answer.block,
    answer.requirement,
    answer.met,
  ]);

const indexOf = (input: {
  byId: BlocksById;
  constitution: Constitution;
}): string =>
  `${[
    HEADER,
    ...roleRecords(),
    ...input.constitution.blocks.map((block) =>
      blockRecord({
        block,
        blocks: input.constitution.blocks,
        byId: input.byId,
      }),
    ),
    ...input.constitution.rules.map((rule) =>
      ruleRecord({
        byId: input.byId,
        rule,
      }),
    ),
    ...input.constitution.requirementAnswers.map(answerRecord),
  ].join('\n')}\n`;

export { indexOf };
